version: "3.8"

services:
  spark:
    build:
      context: ./data-pipeline
      dockerfile: docker/Dockerfile
    image: spark-etl:local

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.2
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      LOCAL_AIRFLOW: "true"
      AIRFLOW__CORE__FERNET_KEY: "Givf721ENayHTpt2WnWs1-w_UPZlPst_kOFy0Fx8pmo="
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey"
    volumes:
      - ./data-pipeline/dags:/opt/airflow/dags
      - ./data-pipeline/spark_jobs:/opt/airflow/spark_jobs
      - ./data-pipeline/scripts:/opt/airflow/scripts
      - ./data-pipeline/data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db upgrade && \
      airflow users create \
        --username admin \
        --password admin \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email admin@example.com --force && \
      airflow scheduler & airflow webserver"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: genai-app:local
    ports:
      - "8000:8000"

volumes:
  postgres-db-volume:
