[tool.ruff]
line-length = 100
exclude = ["build", "dist", ".venv"]

[tool.ruff.lint]
select = ["E", "F", "B", "B"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"