apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app: {{ .Chart.Name }}-backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}-backend
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.backend.servicePort }}
      protocol: TCP
  type: ClusterIP
