apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  # These would typically be injected from external secret management systems
  # For demo purposes, shown as base64 encoded placeholders
  OPENAI_API_KEY: "T1BFTkFJX0FQSV9LRVlfUExBQ0VIT0xERVI="  # "OPENAI_API_KEY_PLACEHOLDER"
  AWS_ACCESS_KEY_ID: "QVdTX0FDQ0VTU19LRVlfSURfUExBQ0VIT0xERVI="  # "AWS_ACCESS_KEY_ID_PLACEHOLDER"
  AWS_SECRET_ACCESS_KEY: "QVdTX1NFQ1JFVF9BQ0NFU1NfS0VZX1BMQUNFSE9MREVSRA=="  # "AWS_SECRET_ACCESS_KEY_PLACEHOLDER"