# Custom Airflow image with project dependencies installed
FROM apache/airflow:3.0.3
USER airflow

# Install project Python dependencies
COPY requirements.txt /opt/airflow/requirements.txt
RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt

