name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ca-central-1
  ECR_REPO: spark-etl
  IMAGE_TAG: latest

jobs:
  build-lint-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install ruff pytest

    - name: Lint code with Ruff
      run: |
        ruff check .

    - name: Run tests
      run: |
        pytest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker image
      run: |
        docker build -t $ECR_REPO:$IMAGE_TAG -f data-pipeline/docker/Dockerfile .
        docker tag $ECR_REPO:$IMAGE_TAG 271111372751.dkr.ecr.ca-central-1.amazonaws.com/$ECR_REPO:$IMAGE_TAG
        docker push 271111372751.dkr.ecr.ca-central-1.amazonaws.com/$ECR_REPO:$IMAGE_TAG