name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ca-central-1

jobs:
  ci:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('data-pipeline/requirements.txt', 'app/requirements.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r data-pipeline/requirements.txt
          pip install -r app/requirements.txt

      - name: Lint with Ruff
        run: ruff check .

      - name: Run tests
        run: |
          pytest --junitxml=pytest-results.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results.xml

      # UI pipeline
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Install UI dependencies
        working-directory: ui
        run: npm ci

      - name: Lint UI
        working-directory: ui
        run: npm run lint

      - name: Test UI
        working-directory: ui
        run: npm test -- --run

      - name: Build UI
        working-directory: ui
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t ci-test-image -f data-pipeline/docker/Dockerfile data-pipeline
